receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 1s
    send_batch_size: 1000

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: atlan_metrics
  
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tenant_id: "atlan"
    labels:
      resource:
        service.name: "service"
      attributes:
        level: "level"
        trace_id: "trace_id"
        span_id: "span_id"
  
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, logging]
    
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
    
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, logging]